default_model: "openai"

models:
  openai:
    name: "openai"
    model_name: "gpt-3.5-turbo"
    base_url: null
    temperature: 0.0
  
  lmstudio:
    name: "lmstudio"
    model_name: "qwen2.5-7b-instruct-1m"
    base_url: "http://127.0.0.1:1234/v1"
    temperature: 0.0

  huggingface:
    name: "huggingface"
    model_name: "meta-llama/Llama-2-7b-chat-hf"
    temperature: 0.3
    quantize_4bit: false
    max_new_tokens: 500
    top_k: 50
    top_p: 0.95