from typing import Protocol, Any

class BaseLLM(Protocol):
    """Interface for simple text/chat LLMs."""
    def name(self) -> str: ...
    def metadata(self) -> dict[str, Any]: ...
    def generate(self, prompt: str) -> str: ...
